# Generated by Django 3.2.19 on 2024-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unhash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashInput', models.CharField(max_length=200)),
                ('hashType', models.CharField(max_length=200)),
            ],
        ),
    ]
