# Generated by Django 3.2.19 on 2024-01-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gethash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashcatmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
